### PR TITLE
Bump Inertia peer dependency

### PR DESCRIPTION
**Pull request by irakan**

### CODE REVIEW

**Comment by reinink** [comment]
Good catch 👍

**Comment by nelson6e65** [comment]
I'm unable to install on @inertiajs/inertia:^0.9.0. Is not compatible?

**Comment by reinink** [comment]
@nelson6e65 Thanks for the reminder. I just published `@inertiajs/progress@0.2.5`, which includes support for `0.9.x`. 👍

**Comment by nelson6e65** [comment]
Thanks

**Pull request merged**
