### PR TITLE
feat: add typings

### PR DESCRIPTION
**Pull request by innocenzi**
I just added this plugin to a TypeScript project, and my IDE just screamed at me. It wanted types, the plugin didn't have types. So I added types. 

I figured I'd share.

### CODE REVIEW

**Comment by AdrianMrn** [comment]
LGTM! @claudiodekker any chance you can merge this?

**Comment by claudiodekker** [comment]
@AdrianMrn It looks good to me, but I'll let @reinink do that instead, because if I start merging things he won't be aware of what's in part of the codebase and what isn't 😉

**Comment by reinink** [comment]
Thanks @innocenzi 👍

**Comment by reinink** [comment]
Now available in `0.2.2`.

**Comment by innocenzi** [comment]
Cool, thanks!

**Pull request merged**
